language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run python -m pytest --cov-report=xml --cov=notas tests/
after_success:
  - codecov
