version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      # Obtenemos codigo del repo
      - checkout
      # Entorno virtual y dependencias
      - run:
          name: Entorno y dependencias
          command: |
            make
      # Ejecucion de los tests
      - run:
          name: Ejecutar tests
          command: |
            make tests
