version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      # Obtenemos codigo del repo
      - checkout
      # Entorno virtual y dependencias
      - run:
          name: Entorno y dependencias
          command: |
	    pip install pipenv
            pipenv install --dev
      # Ejecucion de los tests
      - run:
          name: Ejecutar tests
          command: |
            pipenv run python -m pytest
