version: 2
workflows:
  version: 2
  test:
    jobs:
      - python-3.5
      - python-3.6
      - python-3.7
      - python-3.8
jobs:
  python-3.5: &build-template # Definimos una base de ejecución
    docker:
      - image: circleci/python:3.5
    steps:
      # Obtenemos codigo del repo
      - checkout
      # Entorno virtual y dependencias
      - run:
          name: Entorno y dependencias
          command: |
            make pm2
            make
      # Ejecucion de los tests
      - run:
          name: Ejecutar tests
          command: |
            make tests
      # Actualiza codecov
      - run:
          name: Coverage
          command: |
            make coverage
      # Arranca el microservicio
      - run:
          name: Arranque 
          command: |
            make start
      # Para y borra el microservicio
      - run:
          name: Parada 
          command: |
            make delete
  
  python-3.6:
    <<: *build-template
    docker:
      - image: circleci/python:3.6
  python-3.7:
    <<: *build-template
    docker:
      - image: circleci/python:3.7
  python-3.8:
    <<: *build-template
    docker:
      - image: circleci/python:3.8
